Repository VcDevel/Vc, pull requests merged in 2021-07, with the labels that each got.

#278 Add github actions CI inspired by travis/appveyor scripts
  .github/workflows/ci.yaml
Labels: type: enhancement

#290 Require at least VS2015
  CMakeLists.txt
  cmake/VcMacros.cmake
  cmake/msvc_version.c
Labels: type: code cleanup

#291 MSVC: specify Vc_VDECL explicitly on a few functions
  Vc/avx/detail.h
  Vc/cpuid.h
  Vc/sse/detail.h
  Vc/support.h
Labels: type: bug
